# Generated by Django 3.2.6 on 2021-08-09 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='empresa.departamento'),
        ),
    ]
